language: node_js

node_js:
- 8

notifications:
  email: false

cache:
  directories:
    - node_modules

before_deploy: "yarn build"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
  
deploy:
- provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_OAUTH_TOKEN}
  file_glob: true
  file:
    - build/*
  on:
    tags: true
    all_branches: true

# By default travis will build for PROD, for other envs, uncomment lines below
#env:
#  - REACT_APP_BACKEND_URL = "https://apisupport.landsbankinn.is/Loans/CreditAssessment/v1"
#  - REACT_APP_API_KEY = "APIKEY"